### ISSUE TITLE
Documentation is a bit lacking

### ISSUE THREAD

**Issue by uldics** [ahungry/puny-gui#1]
This is all known to you, but unfortunately not us.
What is needed to build a GUI from scratch? All of the files in the downloaded archive?
How do I start the dog example?
Is it possible to start the binary without having a console open underneath?
How do I compile a new executable?
Can the executable be just one file, or it still needs all the files and folders around it?

**Comment by ahungry** [comment]
I had a blog post/tutorial that goes with this repo, although I seemed to have forgot to include it in the readme:

https://ahungry.com/blog/2020-04-24-Puny-GUI-Puppy-Finder.html

It goes step by step and I believe would answer all your questions, or broaden understanding into what this is/isn't.

**Comment by uldics** [comment]
Excellent! Thank you! Will try ASAP.
